@startuml packages
set namespaceSeparator none
package "cui.display" as cui.display #aliceblue {
}
package "cui.game" as cui.game #aliceblue {
}
package "gui.app" as gui.app #antiquewhite {
}
package "gui.game" as gui.game #antiquewhite {
}
package "logic.board" as logic.board #aquamarine {
}
package "logic.cell" as logic.cell #aquamarine {
}
package "logic.connect_four" as logic.connect_four #aquamarine {
}
package "logic.const" as logic.const #aquamarine {
}
package "logic.point" as logic.point #aquamarine {
}
package "main" as main #burlywood {
}
cui.display --> logic.board
cui.display --> logic.cell
cui.game --> cui.display
cui.game --> logic.connect_four
gui.app --> logic.cell
gui.app --> logic.connect_four
gui.app --> logic.const
gui.app --> logic.point
gui.game --> gui.app
logic.board --> logic.cell
logic.board --> logic.point
logic.connect_four --> logic.const
logic.connect_four --> logic.board
logic.connect_four --> logic.cell
logic.connect_four --> logic.point
logic.const --> logic.point
main --> cui.game
main --> gui.game
@enduml
